version: '3'
services:
    php:
        privileged: true
        depends_on: 
          - mysql
        container_name: php
        build:
            dockerfile: Dockerfile
            context: ./
        working_dir: /var/www/html/magento
        restart: always
        volumes:             
          - ./:/var/www/html/magento
        expose: 
          - "9000"
        ports:
          - "8080:80"
          - "9000:9000"
    nginx:
        container_name: nginx
        image: nginx:stable
        restart: always
        depends_on: 
          - php
        volumes: 
          - ./magento.conf:/etc/nginx/conf.d/default.conf
          - ./:/var/www/html/magento
        expose:
          - "80"
        ports: 
          - "80:80"
          - "8011:8011"
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        cap_add:
          - SYS_NICE 
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - ./db-data:/var/lib/mysql
          - ./my.cnf:/etc/mysql.mycnf
        expose: 
          - "3306"
        ports:
          - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
          - 5000:8080